pandaserver/dataservice/AdderGen.py
pandaserver/taskbuffer/OraDBProxy.py

Increase RAM at job level. Once >30% jobs have been increased, we will increase the task requirement.

Increase RAM improvement for job granularity

---

pandaserver/configurator/Configurator.py
pandaserver/configurator/db_interface.py
pandaserver/configurator/ddm_interface.py
pandaserver/configurator/models.py
templates/DB/DB update scripts/configurator.sql

- Expired usage
- Storage usage timestamp
- State column for site (not filled yet)

Configurator

---

pandaserver/configurator/Configurator.py
pandaserver/configurator/aux.py
pandaserver/configurator/db_interface.py
pandaserver/configurator/models.py
pandaserver/taskbuffer/OraDBProxy.py
pandaserver/taskbuffer/TaskBuffer.py
pandaserver/taskbuffer/Utils.py

Network configurator and site corepower collection

Configurator release

---

pandaserver/jobdispatcher/Watcher.py

in order to take care of e.g. lost heartbeat errors

added call to retrymodule from Watcher

---

pandaserver/configurator/Configurator.py
pandaserver/configurator/aux.py

Has more network metrics and is hosted on a production server

Move to the second NWS json

---

pandaserver/config/panda_config.py
pandaserver/server/panda.py
pandaserver/taskbuffer/MemProxy.py
pandaserver/taskbuffer/OraDBProxy.py
pandaserver/taskbuffer/TaskBuffer.py
pandaserver/userinterface/UserIF.py
templates/panda_server.cfg.rpmnew.template

Reverts PanDAWMS/panda-server#25

Revert "Remove obsoleted memcached code"

---

pandaserver/jobdispatcher/JobDispatcher.py
pandaserver/taskbuffer/GlobalShares.py
pandaserver/taskbuffer/JobSpec.py
pandaserver/taskbuffer/OraDBProxy.py
pandaserver/taskbuffer/TaskBuffer.py

Global shares tree, and methods to tag a share

First step for Global shares 

---

pandaserver/jobdispatcher/JobDispatcher.py
pandaserver/taskbuffer/OraDBProxy.py
pandaserver/test/add.py

Added also the absolute number of getjob and updatejob requests, previously it was the count of nodes/slots

Count for pilot requests that didn't get a job

---

pandaserver/server/panda.py
pandaserver/taskbuffer/OraDBProxy.py
pandaserver/taskbuffer/TaskBuffer.py
pandaserver/userinterface/Client.py
pandaserver/userinterface/UserIF.py

Reactivate task, get job ids and get task status

HC commands 

---

pandaserver/jobdispatcher/JobDispatcher.py
pandaserver/taskbuffer/OraDBProxy.py
pandaserver/taskbuffer/TaskBuffer.py

Store pilot logs directly instead of going through panda logger

Pilotlog direct store

---

pandaserver/brokerage/SiteMapper.py
pandaserver/brokerage/broker.py
pandaserver/configurator/Configurator.py
pandaserver/dataservice/AdderAtlasPlugin.py
pandaserver/dataservice/DataServiceUtils.py
pandaserver/dataservice/DynDataDistributer.py
pandaserver/dataservice/EventPicker.py
pandaserver/dataservice/Finisher.py
pandaserver/dataservice/SetupperAtlasPlugin.py
pandaserver/jobdispatcher/Protocol.py
pandaserver/taskbuffer/DdmSpec.py
pandaserver/taskbuffer/NucleusSpec.py
pandaserver/taskbuffer/OraDBProxy.py
pandaserver/taskbuffer/SiteSpec.py
pandaserver/test/datasetManager.py
pandaserver/test/fileCallbackListener.py
pandaserver/test/finishJob.py
pandaserver/test/testSiteMap.py
pandaserver/userinterface/UserIF.py

Reverts PanDAWMS/panda-server#43

Revert "Panda ddm relation"

---

pandaserver/brokerage/SiteMapper.py
pandaserver/brokerage/broker.py
pandaserver/configurator/Configurator.py
pandaserver/dataservice/AdderAtlasPlugin.py
pandaserver/dataservice/DataServiceUtils.py
pandaserver/dataservice/DynDataDistributer.py
pandaserver/dataservice/EventPicker.py
pandaserver/dataservice/Finisher.py
pandaserver/dataservice/SetupperAtlasPlugin.py
pandaserver/jobdispatcher/Protocol.py
pandaserver/taskbuffer/DdmSpec.py
pandaserver/taskbuffer/NucleusSpec.py
pandaserver/taskbuffer/OraDBProxy.py
pandaserver/taskbuffer/SiteSpec.py
pandaserver/test/datasetManager.py
pandaserver/test/fileCallbackListener.py
pandaserver/test/finishJob.py
pandaserver/test/testSiteMap.py
pandaserver/userinterface/UserIF.py

Reverts PanDAWMS/panda-server#46

Revert "Panda ddm relation2"

---

pandaserver/taskbuffer/OraDBProxy.py
pandaserver/test/add.py

Modifications to run Harvester jobs with MySQL backend

---

pandaserver/taskbuffer/OraDBProxy.py

keep merging jobs only:
1) update it to finished if current esmerge job finished
2) update it to failed if it discard events
not tested, but checked with flake8.

update to finish merging jobs

---

pandaserver/dataservice/DynDataDistributer.py

Implement globbing pattern matching for the --eventPickDS option

---

pandaserver/configurator/new_configurator/schedconfig_handle.py

Mike's update on the schedconfig_handle

Upload new schedconfig_handle

---

pandaserver/jobdispatcher/JobDispatcher.py
pandaserver/jobdispatcher/Protocol.py
pandaserver/taskbuffer/SiteSpec.py
pandaserver/taskbuffer/TaskBuffer.py

- corrected getJob ddmEndpointOut field so the pilot can use the information
- deleted some glexec stuff

pilot_ddm_endpoint:

---

pandaserver/brokerage/broker.py
pandaserver/dataservice/DDM.py
pandaserver/taskbuffer/OraDBProxy.py
pandaserver/taskbuffer/Utils.py
pandaserver/test/datasetCallbackListener.py
pandaserver/test/datasetManager.py
pandaserver/test/fileCallbackListener.py

Fix python3 issues and some bugs

---

pandaserver/taskbuffer/OraDBProxy.py

it's currently the most executed query on all panda

harvester_slots retrieval done for all sites at once 

---

pandaserver/taskbuffer/OraDBProxy.py

With a second thought, can we first try this on one node with utf8-encoding DB connection?

DB support utf8

---

pandaserver/taskbuffer/OraDBProxy.py

The bug blocks harvester to submit more workers
Not sure if it is correct fix though

dbproxy: fix updateWorkers

---

pandaserver/taskbuffer/OraDBProxy.py

I will test this in the morning

dbproxy: true fix updateWorkers

---

pandaserver/daemons/scripts/add_main.py
pandaserver/daemons/scripts/add_sub.py
pandaserver/daemons/scripts/datasetManager.py
pandaserver/daemons/utils.py
pandaserver/taskbuffer/TaskBufferInterface.py

Tested on dev node.
I will test it on atlas-pandaserver-00 on Monday.

Split add daemon and run add_main continuously

---

pandaserver/daemons/master.py
pandaserver/daemons/scripts/add_main.py
pandaserver/daemons/scripts/configurator.py
pandaserver/daemons/scripts/datasetManager.py
pandaserver/daemons/utils.py
pandaserver/taskbuffer/OraDBProxy.py
pandaserver/taskbuffer/TaskBuffer.py
templates/panda_server.cfg.rpmnew.template

This may save some DB sessions for PanDA daemon (although not much related to recent peaks reaching the limit 400 sessions).
Also, it should reduce this error as well: "ORA-02396: exceeded maximum idle time, please connect again"

panda daemon: save some DB sessions

---

Dockerfile
pandaserver/taskbuffer/OraDBProxy.py
pandaserver/taskbuffer/WrappedCursor.py

Related JIRA ticket [Postgres and json columns](https://its.cern.ch/jira/browse/ATLASPANDA-562)

Changes for postgres with json columns

---

ChangeLog.txt
pandaserver/brokerage/broker.py
pandaserver/daemons/scripts/copyArchive.py
pandaserver/jobdispatcher/JobDispatcher.py
pandaserver/taskbuffer/OraDBProxy.py
pandaserver/taskbuffer/TaskBuffer.py

Schedconfig cleanup

---

Dockerfile
PandaPkgInfo.py
pandaserver/server/panda.py
pandaserver/srvcore/CoreUtils.py
pandaserver/taskbuffer/OraDBProxy.py
pandaserver/userinterface/UserIF.py

https://its.cern.ch/jira/browse/ATLASPANDA-609

Content-Type json <-> form-data

---

PandaPkgInfo.py
pandaserver/brokerage/broker.py
pandaserver/daemons/scripts/copyArchive.py
pandaserver/dataservice/Notifier.py
pandaserver/taskbuffer/OraDBProxy.py
templates/init.d/panda_daemon.exe.template
templates/panda_server-httpd-FastCGI.conf.rpmnew.template
templates/panda_server.cfg.rpmnew.template

Details in https://its.cern.ch/jira/browse/ATLASPANDA-623

rearrangement of cache dir, pid, and lock files

---

PandaPkgInfo.py
pandaserver/taskbuffer/PandaDBSchemaInfo.py
pandaserver/test/SchemaChecker.py
templates/init.d/panda_httpd.exe.template

Fixed shellscript to check if schema version is the correct one. Tested on the k8s pod.

ATLASPANDA-656 DB-code compatibilty check

---

pandaserver/taskbuffer/PandaDBSchemaInfo.py
pandaserver/taskbuffer/WrappedCursor.py
pandaserver/test/SchemaChecker.py
setup.py
templates/init.d/panda_httpd.exe.template

Implemented all required changes after the private discussions with Tadashi and Fernando:
- Changed forced exit with a warning message
- Changed the query to look for the 'SERVER' version, not the 'SCHEMA' version
- Changed the comparison between the two versions
-  Sending an email if the pandaEmailNotification var is defined in the panda config file.
An example email can be seen below:

Required changes after private discussion with Tadashi and Fernando

---

pandaserver/daemons/scripts/add_main.py
pandaserver/dataservice/AdderGen.py
pandaserver/taskbuffer/OraDBProxy.py
pandaserver/taskbuffer/TaskBuffer.py

https://its.cern.ch/jira/browse/ATLASPANDA-827

async update on jedi_datasets

---

pandaserver/taskbuffer/OraDBProxy.py

@tmaeno Is this is the desired fix?

updatJob: not insert status log if jobstatus unchanged

---

pandaserver/daemons/scripts/cache_pilots.py
pandaserver/daemons/scripts/cache_schedconfig.py
pandaserver/taskbuffer/OraDBProxy.py

https://its.cern.ch/jira/browse/ATLASPANDA-850

Change behaviour in memory increase for retry module (ignore maxPSS)

---

pandaserver/dataservice/dyn_data_distributer.py

Final beautification of the dyn_data_distributer.py file based on Fernando's comments:
- Removed pd2p_clouds
- Removed filter sites by "test" in the status since we check for 'online' later on
- Removed use_close_sites
- Moved the junk dataset searching into a new function

Final beautification of the dyn_data_distributer.py

---

pandaserver/dataservice/dyn_data_distributer.py

Fixing an issue with event-picking tasks as reported by Dario:
The prior removal of "use_close_sites" actually introduced a bug and changed the logic of the get_candidate_sites function.

 Fixing an issue with event-picking tasks as reported by Dario 

---

pandaserver/jobdispatcher/Protocol.py

In order to fill in resourcetype in harvester's job_table

add resource_type to getJob response

---

pandaserver/daemons/scripts/evpPD2P.py
pandaserver/dataservice/dyn_data_distributer.py
pandaserver/dataservice/event_picker.py

Refactor the EventPicker.py agent [ATLASPANDA-914]:
usual PEP8 things, removed an unused code block, variables rename, removed unused vars and imports, simplification of run() and split into smaller methods.
Pylint reports:
Your code has been rated at 9.18/10 (previous one was 4.65/10)

Refactor the EventPicker.py agent [ATLASPANDA-914]

---

pandaserver/dataservice/ddm.py

Adding forgotten CoreUtils import as it is now needed with the reintroduction of the finger function

Adding CoreUtils back now that we have the finger function

---

pandaserver/dataservice/ddm.py

Fixed bug with overwriting the dataset_name variable

Fixed bug with overwritten dataset_name variable

---

pandaserver/dataservice/ddm.py
pandaserver/dataservice/dyn_data_distributer.py

Hotfix to make event picking tasks work again. Correcting a typo and how we call the rucio API (was passing a wrong argument)

Hotfix to make event picking tasks work again

---

Dockerfile
templates/panda_server-httpd-FastCGI.conf.rpmnew.template
templates/sysconfig/panda_server.sysconfig.rpmnew.template

add options to be able to configure PanDA http server workers and wsgi processes.

add options to tune the http service

---

Dockerfile

Have trf files under /var/trf/user

Have trf files under /var/trf/user

---

PandaPkgInfo.py

Bump panda-server version to 0.3.9

Bump panda-server version to 0.3.9

---

pandaserver/dataservice/adder_gen.py

Removing XML parcing, adding a warning when JSON parcing fails

Removing XML parcing

---

PandaPkgInfo.py
pandaserver/taskbuffer/OraDBProxy.py
pandaserver/taskbuffer/TaskBuffer.py
pandaserver/taskbuffer/wrapped_oracle_conn.py

* connection wrapper for oracle to override context manager protocol
* trust_user in storeJobs
* get_site_mapper in TaskBuffer

for jedi enhancement

---

pandaserver/dataservice/setupper_atlas_plugin.py

Added register_dispatch_datasets function
Pylint score is quite nice for setupper atlas plugin:
Your code has been rated at 9.13/10

Added register_dispatch_datasets function

---

PandaPkgInfo.py
pandaserver/daemons/scripts/copyArchive.py
pandaserver/taskbuffer/OraDBProxy.py
pandaserver/taskbuffer/TaskBuffer.py

* reassignJobs cleanup
* fixed killJobs to trigger closer

* For JEDI to insert jobs to jobsDefined

---

pandaserver/dataservice/ddm.py
pandaserver/taskbuffer/DataCarousel.py

So that Data Carousel does not depend on code in panda-jedi

data carousel: migrate ddm functions from jedi to panda-server

---

pandaserver/dataservice/dyn_data_distributer.py
pandaserver/dataservice/event_picker.py
pandaserver/mcp/mcp_main.py
pandaserver/mcp/mcp_utils.py
pandaserver/srvcore/panda_request.py
pyproject.toml
templates/panda_server-httpd.conf.rpmnew.template
templates/sysconfig/panda_server.sysconfig.rpmnew.template
templates/sysconfig/panda_server_env.systemd.rpmnew.template
templates/systemd/panda_mcp.service.template

* MCP stuff
* traceback for token decode failures

* added EVP_DATASET_LIFETIME

---

pandaserver/api/v1/credential_management_api.py
pandaserver/taskbuffer/DataCarousel.py

(also include adding lock attributes for future implementation)

data carousel: add last_staged_time
